global:
  scrape_interval: 15s          # Intervalo padrão para coleta de métricas.
  evaluation_interval: 30s      # Intervalo para avaliar regras e alertas.

scrape_configs:
  - job_name: 'prometheusnet-api'
    static_configs:
      - targets: ['prometheusnetapi:8080']  # Usando o nome do serviço ou contêiner se estiver em Docker Compose


  # Configuração para monitorar o próprio Prometheus
  - job_name: 'prometheus'      # Nome do job para identificar o Prometheus.
    static_configs:
      - targets: ['localhost:9090']  # Endereço do Prometheus (porta padrão 9090).